from otree.api import *

INITIAL_TARGET_INVENTORY_RETAILER = 0
INITIAL_TARGET_INVENTORY_FACTORY = 0


class Constant(BaseConstants):
    INITIAL_ORDER_T = 4
    CONSTANT_CUSTOMER_DEMAND = 4
    INITIAL_INCOMING_DEMAND = CONSTANT_CUSTOMER_DEMAND

    INITIAL_INVENTORY = 0
    INITIAL_INCOMING_DELIVERY_T = INITIAL_ORDER_T  # this is used as initial delivery from factory to retailer and from production to retailer
    INITIAL_OUTGOING_DELIVERY = INITIAL_ORDER_T

    INITIAL_BACKLOG_DEMANDS = 0
    INITIAL_FULFILLED_DEMAND = 0

    INVENTORY_COST_PER_UNIT = cu(0.5)
    BACKORDER_PENALTY_COST_PER_UNIT = cu(1)
    TURNOVER_PER_UNIT_DELIVERED = cu(1)

    INITIAL_COST_BACKORDERS = cu(0)
    INITIAL_COST_INVENTORY = cu(0)
    INITIAL_TURNOVER = cu(0)

    LEAD_TIME_ORDER_R2F = 2
    LEAD_TIME_DELIVERY_F2R = 2
    LEAD_TIME_PRODUCTION = 3

    MAX_ORDER_QUANTITY = 1000
    MIN_ORDER_QUANTITY = 0

